---
title: Shiny in Markdown
author: Headless Horseman, Still Candyless
date: Today
output: html_document
runtime: shiny
---

# Select Input

```{r select-input}
selectInput(
    inputId='CountrySelection',
    label='Please choose a country',
    choices=list('USA', 'Mexico', 'Canada', 'Serbia', 'South Africa')
)
```

```{r print-state}
renderText(input$CountrySelection)
```

```{r other-inputs}
sliderInput(
    inputId='SliderSample',
    label='This is not from White Castle',
    min=0, max=10, value=5
)

checkboxInput(
    inputId='CheckSample',
    label='Check this out'
)

radioButtons(
    inputId='RadioSample',
    label='Choose one',
    choices=list('A', 'B', 'C')
)

dateInput(
    inputId='DateChoice',
    label='Select a Date'
)

dateRangeInput(
    inputId='DateRangeChoices',
    label='Choose a start and stop'
)
```

# Text INputs

```{r text-inputs}
textInput(
    inputId='TextSample',
    label='Write something',
    placeholder='Something hidden'
)

textAreaInput(
    inputId='TextArea',
    label='Write a little longer'
)

passwordInput(
    inputId='PasswordSample',
    label='Enter the secret'
)

renderText(input$PasswordSample)
```

# Show Data

```{r render-table}
renderTable(mtcars, rownames=FALSE)

renderDataTable(mtcars)

DT::renderDataTable(mtcars)
```

# Plots

```{r render-plot}
renderPlot(
    hist(mtcars$mpg)
)

library(ggplot2)

myColumn <- 'mpg'
renderPlot(
    ggplot(mtcars, aes_string(x=myColumn)) + geom_histogram()
)

selectInput(
    inputId='PlotColumn',
    label='Choose a column',
    choices=names(mtcars)
)

sliderInput(
    inputId='NumBins',
    label='Choose number of bins',
    min=5, max=50, value=20
)

radioButtons(
    inputId='PlotColor',
    label='Choose a color',
    choices=list('red', 'lightgreen'='green', 'blue')
)

renderPlot(
    ggplot(mtcars, aes_string(x=input$PlotColumn)) + 
        geom_histogram(bins=input$NumBins, fill=input$PlotColor)
)
```

